apiVersion: v1
kind: Service
metadata:
  name: {{ include "theai.fullname" . }}-postgres
  labels:
    {{- include "theai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app: {{ include "theai.fullname" . }}-postgres