apiVersion: v2
name: theai
description: THEAI - Monitoring & Vulnerability Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - theai
  - monitoring
  - kubernetes
home: https://github.com/{{ github_username }}/theai
sources:
  - https://github.com/{{ github_username }}/theai
maintainers:
  - name: DevOps Team
    email: aecodinglocal@gmail.com